#!/bin/bash -e
ssh $(cat ssh_args) << EOF
if ! [ -d blabber ]; then
    git clone https://github.com/megahomyak/blabber.git
fi
cd blabber
git pull -f --rebase
cd server
docker rm --force blabber
docker build . -t blabber
docker run -d -p 8011:80 --name blabber --restart unless-stopped blabber
EOF
