#!/bin/bash -e
ssh orange << EOF
if ! [ -d blabber ]; then
    git clone https://github.com/megahomyak/blabber.git
fi
cd blabber
git pull
cd server
docker rm --force blabber
docker build . -t blabber
sudo docker run -d -p 8011:80 --name blabber --restart unless-stopped blabber
EOF
